version: '3'
services:
  zookeeper:
    image: eventuateio/eventuate-zookeeper
    ports:
      - 2181:2181

  kafka:
    image: eventuateio/eventuate-kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
       - ADVERTISED_HOST_NAME=kafka
       - KAFKA_HEAP_OPTS=-Xmx192m -Xms192m
       - ZOOKEEPER_SERVERS=zookeeper:2181

  postgres:
    restart: always
    image: eventuateio/eventuateio-local-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: eventuate
      POSTGRES_PASSWORD: eventuate

  cdcservice:
    image: eventuateio/eventuate-cdc-service
    ports:
      - "8099:8080"
    depends_on:
      - postgres
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/eventuate
      SPRING_DATASOURCE_USERNAME: eventuate
      SPRING_DATASOURCE_PASSWORD: eventuate
      SPRING_DATASOURCE_TEST_ON_BORROW: "true"
      SPRING_DATASOURCE_VALIDATION_QUERY: SELECT 1
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      SPRING_PROFILES_ACTIVE: PostgresWal
      EVENTUATELOCAL_CDC_READER_NAME: PostgresWalReader
      EVENTUATE_CDC_TYPE: EventuateLocal