server:
  port: 8082
spring:
  application:
    name: bms-account-service
  bms-account-service:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/bms_account_service?&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
      username: root
      password: rootpassword
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

eventuatelocal:
  kafka:
    bootstrap:
      servers: localhost:9092
  zookeeper:
    connection:
      string: localhost:2181

management:
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: ALWAYS

logging:
  level:
    io:
    eventuate: DEBUG
    org.springframework: INFO
