server:
  port: 8084
spring:
  application:
    name: bms-customer-service
  bms-customer-service:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/bms_customer_service?&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
      username: root
      password: rootpassword
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

eventuatelocal:
  kafka:
    bootstrap:
      servers: localhost:9092
  zookeeper:
    connection:
      string: localhost:2181

management:
  endpoints:
    health:
      show-details: ALWAYS
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework: INFO